### ISSUE TITLE
add this to p2

### ISSUE THREAD

**Issue by NolanC33** [lmouelle/433sharedtests#4]
@Test
	public void TestSimpleRun() {		
		
		
		int numCustomers = 1;
		int numCooks = 1;
		int numTables = 1;
		int machineCapacity = 1;
		boolean randOrders = false;
		
		Validate.validateSimulation(
				Simulation.runSimulation(
						numCustomers, numCooks, 
						numTables, machineCapacity,
						randOrders
						)
				);
		
	}

**Comment by lmouelle** [comment]
Manually added to SharedTests.java under p2. Pull request next time please.
